imports:
    - { resource: security.yml }
    - { resource: services.yml }

framework:
    #esi:             ~
    translator:      { fallback: en }
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: %kernel.debug%
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: false }
    templating:      { engines: ['twig'] }
    #assets_version: SomeVersionScheme
    default_locale:  %locale%
    trusted_proxies: ~
    session:         ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    exception_controller: BM2SiteBundle:Exception:exception
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    form:
        resources:
            - 'BM2SiteBundle:Form:form_theme.html.twig'

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: %kernel.root_dir%/Resources/java/compiler.jar
        #yui_css:
        #    jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8
        types:
            geometry:   CrEOF\Spatial\DBAL\Types\GeometryType
            point:      CrEOF\Spatial\DBAL\Types\Geometry\PointType
            polygon:    CrEOF\Spatial\DBAL\Types\Geometry\PolygonType
            linestring: CrEOF\Spatial\DBAL\Types\Geometry\LineStringType
        schema_filter:  ~^(?!(geography_columns)|(geometry_columns)|(raster_columns)|(raster_overviews)|(spatial_ref_sys))~
    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true
        dql:
            datetime_functions:
                date_part:          BM2\SiteBundle\DQL\DatePart
            numeric_functions:
                pow:                BM2\SiteBundle\DQL\Pow
                round:              BM2\SiteBundle\DQL\Round
                st_point:           CrEOF\Spatial\ORM\Query\AST\Functions\PostgreSql\STPoint
                st_x:               CrEOF\Spatial\ORM\Query\AST\Functions\PostgreSql\STX
                st_y:               CrEOF\Spatial\ORM\Query\AST\Functions\PostgreSql\STY
                st_asgeojson:       CrEOF\Spatial\ORM\Query\AST\Functions\PostgreSql\STAsGeoJson
                st_astext:          CrEOF\Spatial\ORM\Query\AST\Functions\PostgreSql\STAsText
                st_contains:        CrEOF\Spatial\ORM\Query\AST\Functions\PostgreSql\STContains
                st_difference:      CrEOF\Spatial\ORM\Query\AST\Functions\PostgreSql\STDifference
                st_distance:        CrEOF\Spatial\ORM\Query\AST\Functions\PostgreSql\STDistance
                st_closestpoint:    CrEOF\Spatial\ORM\Query\AST\Functions\PostgreSql\STClosestPoint
                st_dwithin:         CrEOF\Spatial\ORM\Query\AST\Functions\PostgreSql\STDWithin
                st_startpoint:      CrEOF\Spatial\ORM\Query\AST\Functions\PostgreSql\STStartPoint
                st_endpoint:        CrEOF\Spatial\ORM\Query\AST\Functions\PostgreSql\STEndPoint
                st_boundary:        CrEOF\Spatial\ORM\Query\AST\Functions\PostgreSql\STBoundary
                st_area:            CrEOF\Spatial\ORM\Query\AST\Functions\PostgreSql\STArea
                st_length:          CrEOF\Spatial\ORM\Query\AST\Functions\PostgreSql\STLength
                st_buffer:          CrEOF\Spatial\ORM\Query\AST\Functions\PostgreSql\STBuffer
                st_geomfromtext:    CrEOF\Spatial\ORM\Query\AST\Functions\PostgreSql\STGeomFromText
                st_line_interpolate_point:     CrEOF\Spatial\ORM\Query\AST\Functions\PostgreSql\STLineInterpolatePoint
                st_line_locate_point:          CrEOF\Spatial\ORM\Query\AST\Functions\PostgreSql\STLineLocatePoint
                st_line_substring:  CrEOF\Spatial\ORM\Query\AST\Functions\PostgreSql\STLineSubstring
                st_azimuth:         CrEOF\Spatial\ORM\Query\AST\Functions\PostgreSql\STAzimuth
                st_touches:         CrEOF\Spatial\ORM\Query\AST\Functions\PostgreSql\STTouches
                st_crosses:         CrEOF\Spatial\ORM\Query\AST\Functions\PostgreSql\STCrosses
                st_intersects:      CrEOF\Spatial\ORM\Query\AST\Functions\PostgreSql\STIntersects
                st_intersection:    CrEOF\Spatial\ORM\Query\AST\Functions\PostgreSql\STIntersection
                st_makebox2d:       CrEOF\Spatial\ORM\Query\AST\Functions\PostgreSql\STMakeBox2D
                st_makeline:        CrEOF\Spatial\ORM\Query\AST\Functions\PostgreSql\STMakeLine
                st_extent:          CrEOF\Spatial\ORM\Query\AST\Functions\PostgreSql\STExtent
                st_scale:           CrEOF\Spatial\ORM\Query\AST\Functions\PostgreSql\STScale
                st_union:           CrEOF\Spatial\ORM\Query\AST\Functions\PostgreSql\STUnion
                st_split:           CrEOF\Spatial\ORM\Query\AST\Functions\PostgreSql\STSplit
                st_geometryn:       CrEOF\Spatial\ORM\Query\AST\Functions\PostgreSql\STGeometryN


# Swiftmailer Configuration
swiftmailer:
    transport:  %mailer_transport%
    host:       %mailer_host%
    username:   %mailer_user%
    password:   %mailer_password%
    disable_delivery: %mailer_disable%

# Framework
sensio_framework_extra:
    router:  { annotations: true }
    request: { converters: true }
    view:    { annotations: true }
    cache:   { annotations: true }

# FOSUserBundle
fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    use_listener: false
    firewall_name: account
    user_class: BM2\SiteBundle\Entity\User
    service:
        user_manager:   bm2.user_manager
    registration:
        confirmation:
            enabled:    true
            from_email:
                address:        mafserver@lemuriacommunity.org
                sender_name:    Might & Fealty Server
    resetting:
        email:
            from_email:
                address:        mafserver@lemuriacommunity.org
                sender_name:    Might & Fealty Server
    from_email:
        address:        mafserver@lemuriacommunity.org
        sender_name:    Might & Fealty Server
